### ISSUE TITLE
Suggestion: define a palette  and do less invasive theme

### ISSUE THREAD

**Issue by guoquan** [dracula/starship#7]
I believe Dracula is a color scheme and no mean a theme. Starship itself is a theming engine.
Current setup of this repos plays a full role of a theme by hard coding colors (from Dracula) and  even changing prompting character.

Suggestion:
We can just provide the Dracula palette and let starship take the lead.
Something like"

```toml
palette = "darcula"

[palettes.darcula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
```

If someone still want the green lambda prompting character, they are free to add their starship things:

```toml
[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"
```

User is more flexible to hack the starship, and everything is more semantic also.
